name: Test fail steps
on:
  workflow_dispatch:
jobs:
  fail-steps-test:
    runs-on: ubuntu-latest
    steps:
      - name: Fail step
        run: mvn clean test
      - name: Next step
        if: always()
        run: echo "Next step"
      - name: "notify failure"
        if: failure()
        run: echo "Failure"
      - name: "notify complete"
        if: success()
        run: echo "Success"
        
